"""Explicit synthetic fixtures, not results generated by a live ATS or AI."""
from datetime import date,timedelta
from . import store as db
from .schemas import Criterion
from .intelligence import extract_jd
from .domain import digest
from .services import queue_run

JDS=[('Senior Backend Engineer','Develop Java services and PostgreSQL applications. Own Kafka integrations and production incident response. Kubernetes deployment experience preferred.','Engineering · Platform',True),('Production Engineer','Own incident response, observability and Kubernetes deployments. Develop Python automation and CI/CD pipelines. Terraform experience preferred.','Engineering · Reliability',True),('Data Engineer','Develop Python and SQL data pipelines. Build Kafka integrations with PostgreSQL. AWS experience preferred.','Engineering · Data',True)]
NAMES=['Aarav Mehta','Elena Laurent','Maya Kapoor','Daniel Chen','Priya Menon','Oliver Reed','Sofia Martin','Rohan Shah','Amara Okafor','Lucas Weber','Nadia Benali','Arjun Rao','Clara Dubois','Ethan Park','Ishita Sen','Noah Williams','Leila Haddad','Vikram Desai','Anna Kowalski','Kabir Sethi','Sara Jensen','Aditya Nair','Meera Iyer','Thomas Bernard','Ananya Bose','Hugo Moreau','Neha Reddy','Julien Petit','Zara Ali','Arun Pillai']
WORK=[
 ('Backend Engineer','Built Java services with PostgreSQL and Kafka consumers in the payment platform. Owned incident response and restored service after deployment failures. Deployed applications on Kubernetes.','Java, PostgreSQL, Kafka, Kubernetes'),
 ('Software Engineer','Developed JVM services backed by Postgres. Implemented RabbitMQ event delivery and operated container orchestration for customer payments. Diagnosed failures and restored service.','JVM, Postgres, RabbitMQ, container orchestration'),
 ('Platform Engineer','Operated Kubernetes workloads and Prometheus monitoring. Built Python automation, Terraform infrastructure and continuous delivery pipelines. Owned incident response.','Kubernetes, Python, Terraform, Prometheus, CI/CD'),
 ('Data Engineer','Built Python and SQL data pipelines. Implemented Kafka ingestion into PostgreSQL and maintained AWS data workloads.','Python, SQL, Kafka, PostgreSQL, AWS'),
 ('Application Developer','Developed Java services and optimized PostgreSQL queries. Built customer-facing APIs and automated testing.','Java, PostgreSQL, Docker'),
 ('Graduate Developer','Skills: Java, PostgreSQL, Kafka, Kubernetes, Python, SQL. Coursework and introductory tutorials; professional application not described.','Java, PostgreSQL, Kafka, Kubernetes, Python, SQL'),
]

def seed():
    with db.Session.begin() as s:
        if db.all_of(s,'job'):return
        today=date.today()
        jobs=[]
        for n,(title,description,department,internal) in enumerate(JDS):
            criteria=extract_jd(description)
            job=db.add(s,'job',{'title':title,'description':description,'department':department,'internal':internal,'draft':criteria,'rubric_id':None,'synthetic':True},f'job_demo_{n+1}')
            rubric=db.add(s,'rubric',{'job_id':job['id'],'version':1,'criteria':criteria,'approved_at':db.now(),'approved_by':'synthetic-demo-fixture'},f'rubric_demo_{n+1}')
            job=db.put(s,job['id'],{**job,'rubric_id':rubric['id']});jobs.append(job)
        for i,name in enumerate(NAMES):
            source='current_applicant' if i<10 else ('past_applicant' if i<22 else 'employee')
            title,work,skills=WORK[i%len(WORK)]
            evidence=[{'id':'e1','location':'Synthetic resume · paragraph 1','text':name}, {'id':'e2','location':'Synthetic resume · paragraph 2','text':f'{title} | 2022-01 to present. {work}'},{'id':'e3','location':'Synthetic resume · paragraph 3','text':'Skills: '+skills}]
            facts={'name':name,'title':title,'skills':skills.split(', '),'roles':[{'id':'r1','title':title,'start':'2022-01','end':'present','relevant':False,'evidence_ids':['e2']}],'stated_months':None}
            p={'source_type':source,'source_record_id':f'SYN-{i+1:03}','filename':name.lower().replace(' ','_')+'.docx','updated_at':(today-timedelta(days=i*2)).isoformat(),'matching_allowed':True,'retention_expires_at':(today+timedelta(days=180)).isoformat(),'internal_visibility':source=='employee','suppressed':False,'application_status':'rejected' if source=='past_applicant' else 'applied','rejected_at':(today-timedelta(days=20+i)).isoformat() if source=='past_applicant' else None,'active_interview':False,'previous_job_title':'Infrastructure Engineer' if source=='past_applicant' else None,'previous_stage':'Final interview' if i%3==0 else 'Screening','previous_outcome':'Role requirements differed','silver_medalist':source=='past_applicant' and i%3==0,'job_id':jobs[0]['id'] if source=='current_applicant' else None,'facts':facts,'evidence':evidence,'version_id':f'pv_demo_{i+1}','document_hash':digest(evidence),'synthetic':True}
            if i==18:p['rejected_at']=(today-timedelta(days=120)).isoformat()
            if i==19:p['application_status']='interview';p['active_interview']=True
            if i==20:p['matching_allowed']=False
            if i==21:p['retention_expires_at']=(today-timedelta(days=1)).isoformat()
            profile=db.add(s,'profile',p,f'profile_demo_{i+1}')
            db.add(s,'profile_version',{'profile_id':profile['id'],'facts':facts,'evidence':evidence},p['version_id'])
        queue_run(s,jobs[0],db.get(s,jobs[0]['rubric_id']))

if __name__=='__main__':seed()
