import {useState,useEffect} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {api,send,statusLabels,type Row} from '../api';
import {Button} from './ui/button';

export function FreshnessSummary({results}:{results:Row[]}){
 const skills=results.filter(r=>r.category==='skill');
 const dated=skills.filter(r=>r.last_used);
 return <small className="freshness-summary">{dated.length?dated.slice(0,2).map(r=>`${r.requirement}: ${r.last_used==='present'?'ongoing use':r.last_used}`).join(' · '):'Skill use dates need clarification'}{skills.length>dated.length&&` · ${skills.length-dated.length} undated`}</small>;
}

export function SkillFreshness({rows,onEvidence}:{rows:Row[];onEvidence:(r:Row)=>void}){
 if(!rows.length)return null;
 return <details className="insight-section"><summary>When were these skills evidenced?</summary><p className="muted">A dated mention does not prove active use. Dates affect the score only where the approved requirement includes a recency condition.</p><div className="skill-evidence-grid">{rows.map(r=><div key={r.skill}><strong>{r.skill}</strong><span>{r.last_evidenced==='present'?'Ongoing use':r.last_evidenced||r.dated_mention||'Unknown'}</span><small>{r.label}</small><button className="link-text" disabled={!r.evidence_ids.length} onClick={()=>onEvidence({requirement:r.skill,status:r.last_evidenced?'supported':'not_evidenced',rationale:r.label,evidence_ids:r.evidence_ids})}>Read source</button></div>)}</div></details>;
}

export function CareerContext({data,onEvidence}:{data:Row;onEvidence:(r:Row)=>void}){
 if(!data)return null;
 return <section className="insight-section"><h3>Career context</h3><p className="muted">{data.note}</p>{data.title_changes.length?<div className="career-changes">{data.title_changes.map((r:Row,i:number)=><div key={i}><strong>{r.from_title} → {r.to_title}</strong><small>{r.months_between_starts} months between role start dates · title change only</small></div>)}</div>:<p>No dated title changes established.</p>}{data.documented_promotions?.length>0&&<><h4>Explicit promotion claims</h4>{data.documented_promotions.map((p:Row)=><div className="career-changes" key={p.evidence_id}><p>{p.text}</p><small>{p.date||'Promotion date not established'}</small><button className="link-text" onClick={()=>onEvidence({requirement:'Documented promotion claim',status:'supported',rationale:'Resume claim only; no score or leadership-potential inference.',evidence_ids:[p.evidence_id]})}>Read source</button></div>)}{data.promotion_intervals_months.length>0&&<p className="muted">Months between explicitly dated promotion claims: {data.promotion_intervals_months.join(', ')}. Descriptive timing only.</p>}</>}{data.repeated_short_tenures&&<div className="info-strip"><div><strong>Short completed roles to discuss</strong><p>{data.short_completed_roles.length} completed roles lasted under 18 months within the last five years. Contracts, projects and simultaneous jobs may explain this. Ask for context; no score penalty.</p></div></div>}{data.overlapping_roles&&<p className="muted">Some roles overlap. They may be simultaneous assignments; do not assume separate job changes.</p>}{data.roles.some((r:Row)=>r.scope_evidence.length>0)&&<p className="muted">Documented ownership or leadership passages appear in the work history below. These claims do not establish promotion speed or leadership potential.</p>}</section>;
}

export function OtherRoles({profileId,onEvidence}:{profileId:string;onEvidence:(r:Row)=>void}){
 const qc=useQueryClient();const [selected,setSelected]=useState<string[]>([]);
 const {data,error}=useQuery({queryKey:['opportunities',profileId],queryFn:()=>api(`/profiles/${profileId}/opportunities`),refetchInterval:q=>q.state.data?.pending?2000:false});
 useEffect(()=>{setSelected((data?.available_jobs||[]).slice(0,3).map((j:Row)=>j.id))},[profileId,data?.available_jobs?.map((j:Row)=>j.id).join(',')]);
 const run=useMutation({mutationFn:()=>api(`/profiles/${profileId}/opportunities`,send('POST',{job_ids:selected})),onSuccess:()=>qc.invalidateQueries({queryKey:['opportunities',profileId]})});
 useEffect(()=>run.reset(),[profileId]);
 return <details className="insight-section"><summary>Could this candidate fit another role?</summary><p>Assess up to three other approved jobs. This may use the AI allowance; saved assessments are reused. You decide whether to pursue a fit.</p>{data?.available_jobs?.length>0&&<fieldset className="other-job-choices"><legend>Choose up to three roles</legend>{data.available_jobs.map((j:Row)=><label className="checkbox-label" key={j.id}><input type="checkbox" checked={selected.includes(j.id)} disabled={!selected.includes(j.id)&&selected.length>=3} onChange={e=>setSelected(e.target.checked?[...selected,j.id]:selected.filter(id=>id!==j.id))}/>{j.title}</label>)}</fieldset>}<Button variant="outline" disabled={run.isPending||data?.pending>0||!selected.length} onClick={()=>run.mutate()}>{run.isPending||data?.pending?'Assessing other roles…':'Find other job fits'}</Button>{(error||run.error)&&<p className="error" role="alert">{String((error||run.error) instanceof Error?(error||run.error as Error)?.message:error||run.error)}</p>}{data?.original_score!=null&&<p className="muted">Original job: {data.original_job} · {data.original_score}/100</p>}{data?.rows.map((a:Row)=><div className="other-role" key={a.id}><div><Link to={`/jobs/${a.job_id}/requirements`}>{a.job_title}</Link><small>{a.needs_refresh?'Saved assessment needs an update':`Assessed ${a.evaluation_date}`}</small><p>{a.summary}</p><small>Essentials: {a.essentials.supported} supported · {a.essentials.partial} partial · {a.essentials.not_evidenced} unclear · {a.essentials.unmet} unmet</small><details className="score-details"><summary>Review requirements and evidence</summary>{a.results.map((r:Row)=><div className="other-role-criterion" key={r.criterion_id}><strong>{r.requirement}</strong><p>{statusLabels[r.status]} · {r.rationale}</p><button className="link-text" onClick={()=>onEvidence(r)}>Read source ({r.evidence_ids.length})</button></div>)}</details></div><strong>{a.overall_score}<small>/100</small></strong></div>)}{run.isSuccess&&!data?.pending&&!data?.rows.length&&<p>No other eligible approved jobs are available.</p>}{data?.failures.map((f:Row)=><p key={f.job_title} className="error">{f.job_title}: {f.error}</p>)}<p className="muted">{data?.note}</p></details>;
}
