import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,sourceLabels,type Row} from '../api';

export default function Monitoring(){
 const [samples,setSamples]=useState(false);
 const {data,error}=useQuery({queryKey:['monitoring',samples],queryFn:()=>api(`/monitoring?include_samples=${samples}`),refetchInterval:10000});
 return <><div className="page-heading"><div><div className="eyebrow">ASSESSMENT QUALITY</div><h1>Assessment monitoring</h1><p>Review score patterns and information gaps across jobs.</p></div></div><label className="checkbox-label"><input type="checkbox" checked={samples} onChange={e=>setSamples(e.target.checked)}/>Include fictional sample profiles</label>{error&&<p className="error" role="alert">{error instanceof Error?error.message:String(error)}</p>}{data&&<><div className="info-strip">{data.note}</div><div className="section-heading"><h2>{data.assessment_count} assessments · {data.candidate_count} distinct people</h2></div>{!data.assessment_count&&<div className="empty"><h3>No eligible assessments to monitor</h3><p>Assess uploaded resumes, or include fictional samples to explore the dashboard.</p></div>}<div className="monitoring-grid">{data.groups.map((g:Row)=><section className="panel monitoring-pool" key={g.source}><h3>{sourceLabels[g.source]}</h3><p>{g.count} profile/job assessments</p><div className="score-histogram" aria-label={`${sourceLabels[g.source]} score distribution`}>{g.bins.map((b:Row)=><div className="histogram-row" key={b.label}><span>{b.label}</span><div><i style={{width:`${100*b.count/Math.max(g.count,1)}%`}}/></div><strong>{b.count}</strong></div>)}</div><p>{g.essential_unresolved} with unclear essential requirements</p><p>{g.stale} need an assessment update</p><small>{g.mean_coverage==null?'Fewer than five assessments: coverage average withheld.':`Average evidence coverage: ${g.mean_coverage}%`}</small></section>)}</div>{data.trend.length>0&&<section className="panel monitoring-history"><h3>Retained assessment history</h3><p className="muted">Latest profile/job record per month. Changes in job mix, profiles and rubric versions can change averages.</p><div className="table-container"><table><thead><tr><th>Month</th><th>Assessments</th><th>Mean documented match</th><th>Rubric versions</th></tr></thead><tbody>{data.trend.map((r:Row)=><tr key={r.month}><td>{r.month}</td><td>{r.count}</td><td>{r.count<5?'Small sample':`${r.mean_score}/100`}</td><td>{r.rubric_count}</td></tr>)}</tbody></table></div></section>}</>}</>;
}
